---
- name: Gather EC2 facts
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ instance_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: degug
  debug:
     msg: "{{ ec2 }}"

- name: create ami
  ec2_ami:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    instance_id: '{{ item.instance_id }}'
    name: "{{ ami_name }}"
    region: "{{ region }}"
    no_reboot: yes
    delete_snapshot: yes
    wait: yes
    tags:
          Name: "{{ ami_name }}" 
    device_mapping:
      - device_name: '/dev/sda1'
        volume_type: 'gp2'
        size: 8
        delete_on_termination: true
  register: ami_result
  with_items: "{{ ec2.instances }}"

- name: degug
  debug:
     msg: "{{ ami_result }}"