---
- name: Clone code
  git:
    repo: "{{ repo_url }}"
    version: "{{ branch }}"
    dest: "{{ remote_dir }}"
    accept_hostkey: yes
  become: yes
  become_user: dev

# And run setup specific commands...